export const SCHEDULE_SELECTED = 'SCHEDULE_SELECTED';
export const SCHEDULE_FETCH_REQUEST = 'SCHEDULE_FETCH_REQUEST';
export const SCHEDULE_FETCH_SUCCESS = 'SCHEDULE_FETCH_SUCCESS';
export const SCHEDULE_FETCH_FAILURE = 'SCHEDULE_FETCH_FAILURE';
export const SCHEDULE_ADD_REQUEST = 'SCHEDULE_ADD_REQUEST';
export const SCHEDULE_ADD_SUCCESS = 'SCHEDULE_ADD_SUCCESS';
export const SCHEDULE_ADD_FAILURE = 'SCHEDULE_ADD_FAILURE';
export const SCHEDULE_UPDATE_REQUEST = 'SCHEDULE_UPDATE_REQUEST';
export const SCHEDULE_UPDATE_SUCCESS = 'SCHEDULE_UPDATE_SUCCESS';
export const SCHEDULE_UPDATE_FAILURE = 'SCHEDULE_UPDATE_FAILURE';
export const SCHEDULE_DELETE_REQUEST = 'SCHEDULE_DELETE_REQUEST';
export const SCHEDULE_DELETE_SUCCESS = 'SCHEDULE_DELETE_SUCCESS';
export const SCHEDULE_DELETE_FAILURE = 'SCHEDULE_DELETE_FAILURE';

export const USER_FETCH_REQUEST = 'USER_FETCH_REQUEST';
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
export const USER_FETCH_FAILURE = 'USER_FETCH_FAILURE';
export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAILURE = 'USER_SIGNIN_FAILURE';

export const USER_UPDATE_PW_REQUEST = 'USER_UPDATE_PW_REQUEST';
export const USER_UPDATE_PW_SUCCESS = 'USER_UPDATE_PW_SUCCESS';
export const USER_UPDATE_PW_FAILURE = 'USER_UPDATE_PW_FAILURE';

export const USER_UPDATE_MODEL_REQUEST = 'USER_UPDATE_MODEL_REQUEST';
export const USER_UPDATE_MODEL_SUCCESS = 'USER_UPDATE_MODEL_SUCCESS';
export const USER_UPDATE_MODEL_FAILURE = 'USER_UPDATE_MODEL_FAILURE';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE';